name: Compile PS2 ELF

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ps2dev/ps2dev:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile PS2 App
        run: |
          make clean || true
          make

      - name: Upload ELF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS2-ELF
          path: "*.ELF"
          
