name: Compile PS2 ELF

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ps2dev/ps2dev:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: apk add --no-cache make build-base

      - name: Compile PS2 App
        run: |
          make clean || true
          make
        env:
          PS2DEV: /usr/local/ps2dev
          PS2SDK: /usr/local/ps2dev/ps2sdk
          GSKIT: /usr/local/ps2dev/gsKit
          PATH: /usr/local/ps2dev/bin:/usr/local/ps2dev/ee/bin:/usr/local/ps2dev/iop/bin:/usr/local/ps2dev/dvp/bin:/usr/local/ps2dev/ps2sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

      - name: Upload ELF Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PS2-ELF
          path: "*.ELF"
          
